classdef testUnpack < matlab.unittest.TestCase

    properties (TestParameter)
        params = { ...
            struct( ...
            'channel_time', 5, ...
            'coeff', 1, ...
            'fc', 10e3, ...
            'fs_delay', 8e3, ...
            'fs_time', 20, ...
            'has_f_resamp', false, ...
            'has_theta_hat', false, ...
            'n_path', 8, ...
            'R', 4e3, ...
            'Tmp', 10e-3, ...
            'velocity', -2),...
            struct( ...
            'channel_time', 5, ...
            'coeff', 1, ...
            'fc', 15e3, ...
            'fs_delay', 16e3, ...
            'fs_time', 20, ...
            'has_f_resamp', true, ...
            'has_theta_hat', false, ...
            'n_path', 10, ...
            'R', 8e3, ...
            'Tmp', 20e-3, ...
            'velocity', 2),...
            struct( ...
            'channel_time', 5, ...
            'coeff', 1, ...
            'fc', 15e3, ...
            'fs_delay', 16e3, ...
            'fs_time', 20, ...
            'has_f_resamp', true, ...
            'has_theta_hat', true, ...
            'n_path', 10, ...
            'R', 8e3, ...
            'Tmp', 20e-3, ...
            'velocity', 2),...
            struct( ...
            'channel_time', 5, ...
            'coeff', 1, ...
            'fc', 15e3, ...
            'fs_delay', 8e3, ...
            'fs_time', 10, ...
            'has_f_resamp', false, ...
            'has_theta_hat', true, ...
            'n_path', 6, ...
            'R', 4e3, ...
            'Tmp', 20e-3, ...
            'velocity', -1.5),...
            };

    end

    methods (TestMethodSetup)
        function setRandomSeed(~)
            rng(1994);
        end
    end

    methods (Test)

        function testUnpackFunction(~, params)
            % close all;

            %% Random channel
            path_delay = [0, randsamples(pi/3:params.Tmp*1e3, params.n_path-1)].' / 1e3;
            path_delay = path_delay - min(path_delay);
            path_gain = exp(-path_delay*params.coeff./params.Tmp);
            c_p = path_gain .* exp(-1j*2*pi*(params.fc)*path_delay);

            %% Populate the channel matrix
            h_hat = zeros(ceil(params.fs_delay*params.Tmp*1.5), 1, round(params.channel_time*params.fs_time));
            h_hat(round((path_delay + 0.2 * params.Tmp)*params.fs_delay), 1, :) = repmat(c_p, 1, size(h_hat, 3));
            f_resamp = 1/(1 + params.velocity / 1545);
            a = 1 - 1 / f_resamp;
            t = 1:round(params.channel_time*params.fs_delay);
            theta_hat = -a * 2 * pi * params.fc * t / params.fs_delay;

            channel = struct;
            channel.h_hat = h_hat;
            channel.params.fs_delay = params.fs_delay;
            channel.params.fs_time = params.fs_time;
            channel.params.fc = params.fc;
            channel.version = 1.0;

            if params.has_theta_hat
                channel.theta_hat = theta_hat;
            end
            if params.has_f_resamp
                channel.f_resamp = f_resamp;
            end
            if params.has_f_resamp && params.has_theta_hat
                channel.theta_hat = zeros(size(channel.theta_hat));
            end

            fs_delay = params.fs_delay;
            fs_time = params.fs_delay * 0.01;
            array_index = 1;
            unpacked = unpack(fs_time, array_index, channel, 0.3, 0.3);

            delay_axis = (0:size(unpacked, 1) - 1) ./ fs_delay;
            time_axis = (0:size(unpacked, 3) - 1) ./ fs_time;

            figure
            imagesc(delay_axis*1e3, time_axis, 20*log10(squeeze(abs(unpacked(:, 1, :))).'), [-30, 0])
            xlabel('Delay [ms]')
            ylabel('Time [s]')

        end

    end
end
function samples = randsamples(population, num)
rand_index = randperm(length(population));
samples = population(rand_index(1:num));
end
