name: CI
on:
  workflow_dispatch:
  push:
    paths:
      - 'src/*.m'
      - 'tests/*.m'
env:
  MLM_LICENSE_TOKEN: ${{ secrets.MLM_LICENSE_TOKEN }}
jobs:
  test_r2021a:
    name: Test-R2021a
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2021a
          products: >
            Signal_Processing_Toolbox
      - name: Run tests
        uses: matlab-actions/run-tests@v2
        with:
          source-folder: src
          select-by-folder: test

  test_latest:
    name: Test-latest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: >
            Signal_Processing_Toolbox
      - name: Run tests
        uses: matlab-actions/run-tests@v2
        with:
          source-folder: src
          select-by-folder: test
          code-coverage-cobertura: code-coverage/coverage.xml
      - uses: codecov/codecov-action@v4
        with:
          file: code-coverage/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
